name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          modules: 'qtcharts'

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DENKAS_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        working-directory: ./build
        run: ctest --build-config Release --output-on-failure

  lint-check:
    name: Clang-Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          find . \
            -path './app/src/vendor' -prune -o \
            -type f \( -iname '*.h' -o -iname '*.cpp' \) -print0 \
          | xargs -0 --no-run-if-empty clang-format --dry-run -Werror